name: Create Gallery

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  run:
    name: Create Gallery
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.5.0
    - name: Preparing the environment
      run: |
        sudo apt install imagemagick jhead
    - name: Creating Gallery
      run: |
        cd ikun
        bash gallery.sh
    - name: Pushing
      run: |
        cd ikun/output
        git init
        